site_name: PwnCrypt Ransomware Hunt Lab
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
nav:
  - Home: docs/index.md
  - Setup Azure VM: docs/setup-azure-vm.md
  - Simulate Attack: docs/simulate-attack.md
  - Detections: docs/detections.md
  - Investigation: docs/investigation.md
  - Response & Recovery: docs/response-and-recovery.md
  - FAQ: docs/faq.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
